version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: api-db
    environment:
      MYSQL_ROOT_PASSWORD: Fechita1
      MYSQL_DATABASE: validacion_rut
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: Fechita1
      DATABASE_NAME: validacion_rut
    command: "./wait-for-it.sh db:3306 -- npm run start:dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
